### ISSUE TITLE
osm2pgrouting help page is out of date

### ISSUE THREAD

**Issue by robe2** [pgRouting/website#19]
http://pgrouting.org/docs/tools/osm2pgrouting.html

It doesn't show new features and shows old commandline syntax.  I think all for example now require -- like  --host, --user  (instead of -host , -user).

Missing schema and some other stuff.

**Comment by dkastl** [comment]
You're right.
Maybe we should just remove this page from the website?
Adding it to docs.pgRouting.org could be better.
