### ISSUE TITLE
documentation links

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#24]
in the website it shows: 
- pgRouting versions 2.x (current)
- pgRouting versions 1.x (deprecated)

the correct documentation link for all versions is:
- http://docs.pgrouting.org/

the documentation of 1.x looks like the website, it doesn't look like in the documentation

**Comment by MarPetra** [comment]
fixed

**Comment by cvvergara** [comment]
The lines are in a `..toctree::`
```
.. toctree::
        :maxdepth: 1

        pgRouting versions 2.x (current) <http://docs.pgrouting.org>
        pgRouting versions 1.x (deprecated) <http://docs.pgrouting.org>
```
How do I fix that?

**Comment by cvvergara** [comment]
Fix like this:
```
* pgRouting documentation <http://docs.pgrouting.org>
* pgRouting latest <http://docs.pgrouting.org/latest>
```
