### ISSUE TITLE
Downloads dont include from version 2.3 

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#25]
in this link: 
- https://pgrouting.org/download.html

there is this link:
- https://launchpad.net/~georepublic/+archive/ubuntu/pgrouting-unstable

the available versions for downloads are  2.1.0 and 2.2.3

**Comment by cvvergara** [comment]
Link on how to download for Debian an Ubuntu
https://github.com/pgRouting/pgrouting/wiki/Download:-Debian-and-Ubuntu

**Comment by cvvergara** [comment]
Fix like:
```
Debian an Ubuntu
* https://github.com/pgRouting/pgrouting/wiki/Download:-Debian-and-Ubuntu
```
