### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#26]
in this link:
https://pgrouting.org/download.html

there is this link (that takes you nowhere):
https://admin.fedoraproject.org/pkgdb/acls/name/pgRouting

**Comment by cvvergara** [comment]
change
https://admin.fedoraproject.org/pkgdb/acls/name/pgRouting
to
https://apps.fedoraproject.org/packages/pgRouting

**Comment by cvvergara** [comment]
it looks now:
*    Fedora Project: http://fedoraproject.org/wiki/GIS (https://admin.fedoraproject.org/pkgdb/acls/name/pgRouting)

change to

* Fedora Project:
  * pgRouting: https://apps.fedoraproject.org/packages/pgRouting
  * All GIS: http://fedoraproject.org/wiki/GIS

**Comment by MarPetra** [comment]
fixed
