### ISSUE TITLE
dead japanese link

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#27]
in this link:
https://pgrouting.org/download.html

there are this dead link in japanese (in [2007/10/15] pgRouting-1.0_win32.zip ):
http://files.postlbs.org/pgrouting/binaries/pgRouting-1.0_win32.zip

**Comment by cvvergara** [comment]
@robe2 
We are going to fix the documentation, can you recheck the section for Windows Binaries to make it more generalized.

**Comment by cvvergara** [comment]
link fro download for windows
https://github.com/pgRouting/pgrouting/wiki/Download:-Windows

**Comment by cvvergara** [comment]
Fix like:
Windows Binaries
* https://github.com/pgRouting/pgrouting/wiki/Download:-Windows

**Comment by cvvergara** [comment]
All things that are there about windows, please remove. Just keep the simple solution
