### ISSUE TITLE
documentation of 1.x

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#28]
in this page:
https://pgrouting.org/documentation.html

it reads:
pgRouting versions 1.x (deprecated)

and takes you to:
https://pgrouting.org/docs/1.x/index.html
that is on the website.

The documentation of 1.x is in 
http://docs.pgrouting.org/1.x/en/index.html

**Comment by MarPetra** [comment]
fixed

**Comment by cvvergara** [comment]
Related to #24 
Link to that documentation 1.x has to be removed.
#64 removes it
