### ISSUE TITLE
workshop links

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#29]
in this link:
https://pgrouting.org/documentation.html#workshops-tutorials
it reads:
- pgRouting Workshop for v2.x (English)
- pgRouting Workshop for v1.05 (Français)

the first one takes you to a general workshop site, but the second takes you to:
http://postgis.fr/chrome/site/docs/workshop-routing-foss4g/docs/_build/html/index.html
and that link sould be in the workshop site

**Comment by cvvergara** [comment]
fix like this
```
Workshops
* pgRouting workshops: https://workshop.pgrouting.org/
```
and open an issue in workshops to mention that the fillowing link:
http://postgis.fr/chrome/site/docs/workshop-routing-foss4g/docs/_build/html/index.html
is missing on the workshop index
