### ISSUE TITLE
How to/ handle one-way streets

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#38]
Is the information outdated?, current? are we keeping?
http://pgrouting.org/docs/howto/oneway.html

**Comment by cvvergara** [comment]
Is v2.0

**Comment by MarPetra** [comment]
![image](https://user-images.githubusercontent.com/39493413/72738391-177d9d80-3b67-11ea-8757-16d752f16594.png)

**Comment by MarPetra** [comment]
![image](https://user-images.githubusercontent.com/39493413/72738616-92df4f00-3b67-11ea-90f4-cfc3322f3f0c.png)

**Comment by MarPetra** [comment]
![image](https://user-images.githubusercontent.com/39493413/72738705-c326ed80-3b67-11ea-944a-819263a7c986.png)
