### ISSUE TITLE
How to/ Network data validation

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#45]
Is the information outdated?, current? are we keeping?
http://pgrouting.org/docs/howto/validation.html

**Comment by cvvergara** [comment]
![image](https://user-images.githubusercontent.com/5035290/71936588-8e7e6380-316f-11ea-9078-a99522ff4274.png)

**Comment by cvvergara** [comment]
![image](https://user-images.githubusercontent.com/5035290/71936720-e3ba7500-316f-11ea-9263-5933302c1b34.png)
