### ISSUE TITLE
pgRouting Gallery/ Examples and Demos/ ridethecity

### ISSUE THREAD

**Issue by MarPetra** [pgRouting/website#50]
pgRouting Gallery -> Examples and Demos (http://pgrouting.org/gallery.html)

find the safest bike route...
--> https://www.ridethecity.com/
- Is the information outdated?, current? are we keeping?

**Comment by cvvergara** [comment]
Lets move all the gallery to the wiki
Related issues:
#51 #52 #53 #54 #55 #56 #57 #58 #59 #60  

If the links are dead links remove the link.
You can make one PR when:
All links are here:
https://github.com/pgRouting/pgrouting/wiki/Using-pgRouting
And
In the gallery page you put this:
```
The gallery can be found here:
https://github.com/pgRouting/pgrouting/wiki/Using-pgRouting
```
